theme: jekyll-theme-slate
title: Articles, Snippets and More
description: Bookmark this to keep an eye on my project updates!

domain: dave-c-ross.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://dave-c-ross.github.io  # the base hostname and protocol for your site, e.g. http://example.com
#baseurl: /REPOSITORY-NAME/      # place folder name if the site is served in a subfolder

markdown: GFM